#포트 설정
server:
  port: 8002

spring:
  config:
    import: file:.env[.properties]
  application:
    name: auth-service

  redis:
    host: "${REDIS_HOST}"
    port: "${REDIS_PORT}"
    password: "${REDIS_PASSWORD}"


#유레카 클라이언트 등록
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_URL}"


#JWT 설정
jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: 3600000
  refresh:
    expiration: 604800000